apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:enmasse-operator
  labels:
    app: enmasse
rules:
  - apiGroups: [ "oauth.openshift.io" ]
    resources: [ "oauthclients" ]
    verbs: [ "create", "get", "update", "list", "watch" ]
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaces", "addresses" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices" ]
    resourceNames: [ "v1alpha1.enmasse.io", "v1beta1.enmasse.io" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
